# cairo_gen/circuits/mlkem_mul.py
"""
ML-KEM NTT-domain multiplication circuit generators.

Generates fully-unrolled Cairo functions for:
  - mul_ntt_pairs: 128 pair-wise multiplies with baked-in gammas
  - inner_product_k3: fused inner product of 3 pair-wise multiplies
"""
from cairo_gen import BoundedIntCircuit
from cairo_gen.circuit import BoundedIntVar
from mlkem_py.constants import Q, gammas


class MulNttPairsCircuitGenerator:
    """Generate circuit for pair-wise NTT-domain multiplication."""

    Q = Q  # 3329

    def __init__(self):
        self.circuit = BoundedIntCircuit("mul_ntt_pairs_inner", modulus=self.Q)

    def _pair_mul(
        self,
        a0: BoundedIntVar, a1: BoundedIntVar,
        b0: BoundedIntVar, b1: BoundedIntVar,
        gamma: BoundedIntVar,
    ) -> tuple[BoundedIntVar, BoundedIntVar]:
        """
        Multiply two degree-1 polynomials mod (X^2 - gamma):
          c0 = a0*b0 + a1*b1*gamma
          c1 = a0*b1 + a1*b0
        """
        a0b0 = a0 * b0
        a1b1 = a1 * b1
        a1b1g = a1b1 * gamma
        c0 = a0b0 + a1b1g

        a0b1 = a0 * b1
        a1b0 = a1 * b0
        c1 = a0b1 + a1b0

        return c0, c1

    def generate(self, mode: str = "felt252") -> str:
        self.circuit = BoundedIntCircuit("mul_ntt_pairs_inner", modulus=self.Q)

        # Register gamma constants
        for i, g in enumerate(gammas):
            if g not in self.circuit.constants:
                self.circuit.register_constant(g, f"G{i}")
        self.circuit.register_constant(self.Q, "Q")

        # Create inputs: f[0..255], g[0..255]
        f_inputs = [self.circuit.input(f"f{i}", 0, self.Q - 1) for i in range(256)]
        g_inputs = [self.circuit.input(f"g{i}", 0, self.Q - 1) for i in range(256)]

        # 128 pair-wise multiplies
        for i in range(128):
            gamma_val = gammas[i]
            gamma_var = self.circuit.constant(gamma_val, f"gamma_{i}")

            c0, c1 = self._pair_mul(
                f_inputs[2*i], f_inputs[2*i+1],
                g_inputs[2*i], g_inputs[2*i+1],
                gamma_var,
            )
            self.circuit.output(c0.reduce(), f"r{2*i}")
            self.circuit.output(c1.reduce(), f"r{2*i+1}")

        self.circuit.print_summary()
        return self.circuit.compile(mode=mode)

    def generate_full(self, mode: str = "felt252") -> str:
        inner_code = self.generate(mode=mode)
        header = """// Auto-generated by cairo_gen/circuits/mlkem_mul.py
// DO NOT EDIT MANUALLY

"""
        wrapper = self._generate_wrapper()
        return header + inner_code + wrapper

    def _generate_wrapper(self) -> str:
        f_params = ", ".join(f"f{i}" for i in range(256))
        g_params = ", ".join(f"g{i}" for i in range(256))
        f_args = ", ".join(f"upcast(f{i})" for i in range(256))
        g_args = ", ".join(f"upcast(g{i})" for i in range(256))
        r_names = ", ".join(f"r{i}" for i in range(256))
        r_items = ", ".join(f"r{i}" for i in range(256))

        return f"""
/// Pair-wise NTT multiply with baked-in gamma constants.
/// Takes two Span<Zq> of length 256, returns Array<Zq> of length 256.
pub fn mul_ntt_pairs_256(mut f: Span<Zq>, mut g: Span<Zq>) -> Array<Zq> {{
    let f_box = f.multi_pop_front::<256>().expect('expected 256 f');
    let [{f_params}] = f_box.unbox();
    let g_box = g.multi_pop_front::<256>().expect('expected 256 g');
    let [{g_params}] = g_box.unbox();

    let ({r_names}) = mul_ntt_pairs_inner({f_args}, {g_args});

    array![{r_items}]
}}
"""


class InnerProductK3CircuitGenerator:
    """Generate fused inner product circuit for k=3."""

    Q = Q

    def __init__(self):
        self.circuit = BoundedIntCircuit("inner_product_k3_inner", modulus=self.Q)

    def generate(self, mode: str = "felt252") -> str:
        self.circuit = BoundedIntCircuit("inner_product_k3_inner", modulus=self.Q)

        # Register gamma constants
        for i, g in enumerate(gammas):
            if g not in self.circuit.constants:
                self.circuit.register_constant(g, f"G{i}")
        self.circuit.register_constant(self.Q, "Q")

        # 6 input polynomials: a0, a1, a2 and b0, b1, b2 (each 256 elements)
        a_inputs = []
        b_inputs = []
        for k in range(3):
            a_inputs.append([
                self.circuit.input(f"a{k}_{i}", 0, self.Q - 1)
                for i in range(256)
            ])
            b_inputs.append([
                self.circuit.input(f"b{k}_{i}", 0, self.Q - 1)
                for i in range(256)
            ])

        # Compute sum of 3 pair-wise multiplies
        for i in range(128):
            gamma_val = gammas[i]
            gamma_var = self.circuit.constant(gamma_val, f"gamma_{i}")

            # Accumulate across k=0,1,2
            acc_c0 = None
            acc_c1 = None
            for k in range(3):
                a0 = a_inputs[k][2*i]
                a1 = a_inputs[k][2*i+1]
                b0 = b_inputs[k][2*i]
                b1 = b_inputs[k][2*i+1]

                a0b0 = a0 * b0
                a1b1g = a1 * b1 * gamma_var
                c0 = a0b0 + a1b1g

                a0b1 = a0 * b1
                a1b0 = a1 * b0
                c1 = a0b1 + a1b0

                if acc_c0 is None:
                    acc_c0 = c0
                    acc_c1 = c1
                else:
                    acc_c0 = acc_c0 + c0
                    acc_c1 = acc_c1 + c1

            self.circuit.output(acc_c0.reduce(), f"r{2*i}")
            self.circuit.output(acc_c1.reduce(), f"r{2*i+1}")

        self.circuit.print_summary()
        return self.circuit.compile(mode=mode)

    def generate_full(self, mode: str = "felt252") -> str:
        inner_code = self.generate(mode=mode)
        header = """// Auto-generated by cairo_gen/circuits/mlkem_mul.py
// DO NOT EDIT MANUALLY

"""
        wrapper = self._generate_wrapper()
        return header + inner_code + wrapper

    def _generate_wrapper(self) -> str:
        # Inner function input order: a0[0..255], b0[0..255], a1[0..255], b1[0..255], a2[0..255], b2[0..255]
        # (interleaved by k: a_k then b_k)
        pop_blocks = []
        inner_args_parts = []

        for prefix in ["a0", "b0", "a1", "b1", "a2", "b2"]:
            params = ", ".join(f"{prefix}_{i}" for i in range(256))
            args = ", ".join(f"upcast({prefix}_{i})" for i in range(256))
            pop_blocks.append(
                f"    let {prefix}_box = {prefix}.multi_pop_front::<256>().expect('expected 256');\n"
                f"    let [{params}] = {prefix}_box.unbox();"
            )
            inner_args_parts.append(args)

        r_names = ", ".join(f"r{i}" for i in range(256))
        r_items = ", ".join(f"r{i}" for i in range(256))
        inner_args = ", ".join(inner_args_parts)
        pops = "\n".join(pop_blocks)

        return f"""
/// Fused inner product of 3 pair-wise NTT multiplies.
/// Computes sum_k(a[k] * b[k]) in NTT domain with baked-in gammas.
pub fn inner_product_k3_256(
    mut a0: Span<Zq>, mut a1: Span<Zq>, mut a2: Span<Zq>,
    mut b0: Span<Zq>, mut b1: Span<Zq>, mut b2: Span<Zq>,
) -> Array<Zq> {{
{pops}

    let ({r_names}) = inner_product_k3_inner({inner_args});

    array![{r_items}]
}}
"""
