[package]
name = "mlkem"
version = "0.1.0"
edition = "2024_07"

[lib]

[[target.executable]]
name = "bench_encaps_setup"
function = "mlkem::bench::bench_encaps_setup"
sierra = true

[[target.executable]]
name = "bench_encaps"
function = "mlkem::bench::bench_encaps"
sierra = true

[[target.executable]]
name = "bench_decaps_setup"
function = "mlkem::bench::bench_decaps_setup"
sierra = true

[[target.executable]]
name = "bench_decaps"
function = "mlkem::bench::bench_decaps"
sierra = true

[dependencies]
corelib_imports = "0.1.2"
cairo_execute = "2.15.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.55.0" }
assert_macros = "2.15.1"
