# tests/compilable_circuits/test_mlkem_ntt.py
"""Tests for ML-KEM NTT circuit generator."""
import pytest
import random
from cairo_gen.circuits.mlkem_ntt import MlkemNttCircuitGenerator
from mlkem_py.ntt import ntt as reference_ntt
from mlkem_py.constants import Q


class TestConstantRegistration:
    """Test twiddle factor constant registration."""

    def test_q_registered(self):
        gen = MlkemNttCircuitGenerator(n=256)
        gen._register_constants()
        assert Q in gen.circuit.constants
        assert gen.circuit.constants[Q] == "Q"

    def test_zetas_registered(self):
        """127 zeta values (zetas[1..127]) are registered."""
        gen = MlkemNttCircuitGenerator(n=256)
        gen._register_constants()
        # zetas[1] = 1729
        assert 1729 in gen.circuit.constants


def _build_circuit():
    """Build and return a traced NTT circuit."""
    gen = MlkemNttCircuitGenerator(n=256)
    gen._register_constants()
    inputs = [gen.circuit.input(f"f{i}", 0, Q - 1) for i in range(256)]
    outputs = gen._ntt_iterative(inputs)
    for i, out in enumerate(outputs):
        gen.circuit.output(out.reduce(), f"r{i}")
    return gen


@pytest.fixture(scope="module")
def ntt_256_circuit():
    """Build n=256 circuit once for all tests in this module."""
    return _build_circuit()


class TestCorrectness:
    """Circuit simulation matches reference NTT."""

    @pytest.mark.parametrize("seed", list(range(10)))
    def test_random_inputs(self, ntt_256_circuit, seed):
        rng = random.Random(seed)
        test_input = [rng.randint(0, Q - 1) for _ in range(256)]
        expected = reference_ntt(test_input[:])
        actual = ntt_256_circuit.simulate(test_input[:])
        assert actual == expected, (
            f"seed={seed}: first mismatch at index "
            f"{next(i for i in range(256) if actual[i] != expected[i])}"
        )

    def test_all_zeros(self, ntt_256_circuit):
        actual = ntt_256_circuit.simulate([0] * 256)
        assert actual == [0] * 256

    def test_all_ones(self, ntt_256_circuit):
        test_input = [1] * 256
        expected = reference_ntt(test_input[:])
        actual = ntt_256_circuit.simulate(test_input[:])
        assert actual == expected

    def test_all_max(self, ntt_256_circuit):
        test_input = [Q - 1] * 256
        expected = reference_ntt(test_input[:])
        actual = ntt_256_circuit.simulate(test_input[:])
        assert actual == expected

    def test_single_nonzero_first(self, ntt_256_circuit):
        test_input = [1] + [0] * 255
        expected = reference_ntt(test_input[:])
        actual = ntt_256_circuit.simulate(test_input[:])
        assert actual == expected

    def test_sequential_values(self, ntt_256_circuit):
        test_input = list(range(256))
        expected = reference_ntt(test_input[:])
        actual = ntt_256_circuit.simulate(test_input[:])
        assert actual == expected

    def test_outputs_in_valid_range(self, ntt_256_circuit):
        rng = random.Random(999)
        test_input = [rng.randint(0, Q - 1) for _ in range(256)]
        actual = ntt_256_circuit.simulate(test_input)
        for i, val in enumerate(actual):
            assert 0 <= val < Q, f"output[{i}] = {val} out of range [0, {Q})"

    def test_circuit_stats(self, ntt_256_circuit):
        stats = ntt_256_circuit.circuit.stats()
        assert stats["num_operations"] > 2000, "Expected >2000 operations for n=256"
        assert stats["max_bits"] <= 252, "Max bits must fit in felt252"


class TestCodeGeneration:
    """Test Cairo code generation."""

    def test_generate_felt252_has_correct_structure(self):
        gen = MlkemNttCircuitGenerator(n=256)
        code = gen.generate(mode="felt252")
        assert "pub fn ntt_256_inner(" in code
        assert "felt252" in code
        assert "SHIFT" in code

    def test_generate_full_includes_wrapper(self):
        gen = MlkemNttCircuitGenerator(n=256)
        code = gen.generate_full(mode="felt252")
        assert "fn ntt_256_inner(" in code
        assert "pub fn ntt_256(mut f: Span<Zq>)" in code
        assert "multi_pop_front::<256>()" in code
        assert "// Auto-generated by cairo_gen/circuits/mlkem_ntt.py" in code


class TestRegenerateCli:
    """Test CLI integration."""

    def test_cli_generates_file(self, tmp_path):
        import subprocess
        result = subprocess.run(
            [
                "python3", "-m", "cairo_gen.circuits.regenerate",
                "mlkem_ntt",
                "--output-dir", str(tmp_path),
            ],
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert result.returncode == 0, f"CLI failed: {result.stderr}"
        output_file = tmp_path / "ntt_felt252.cairo"
        assert output_file.exists(), "Output file not created"
        content = output_file.read_text()
        assert "pub fn ntt_256(" in content
        assert "ntt_256_inner" in content
